[package]
name = "render-tiles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "render"
crate-type = ["dylib"]

[dependencies]

[dependencies.render-api]
path = "../render-api"
package = "render-api"